config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "games#index"
  resources :games, only: [:index, :new, :create]
  resources :game_tweets, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :game_title
  has_one_attached :image

  belongs_to :user

  validates :game_title_id, numericality: { other_than: 0 }
end

app/models/game_title.rb
class GameTitle < ActiveHash::Base
  self.data = [
    { id: 1, name: 'グランブルーファンタジー', image_path: 'grablulogo.png'},
    { id: 2, name: 'プリンセスコネクトRe:Dive', image_path: 'priconelogo.png'},
    { id: 3, name: 'ウマ娘プリティーダービー', image_path: 'umamusumelogo.png'}
  ]

  include ActiveHash::Associations
  has_many :games
  has_many :game_tweets
end

app/models/game_tweet.rb
class GameTweet < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :game_title
  belongs_to :user

  validates :tweet, presence: true
  validates :game_title_id, numericality: { other_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games
  has_many :game_tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

end

app/controllers/game_tweets_controller.rb
class GameTweetsController < ApplicationController

  def index
    @game = Game.where(game_title_id: params[:game_title_id])
    set_mygame
    @game_tweets = GameTweet.find_by(game_title_id: params[:game_title_id])
    @game_tweet = GameTweet.new
  end

  def create
    @game_tweet = GameTweet.new(tweet_params)
    @game_tweet.game_title_id = params[:game_title_id]
    if @game_tweet.valid?
      @game_tweet.save
      redirect_to game_tweets_path(game_title_id: params[:game_title_id])
    else
      render :index, status: :unprocessable_entity
    end
  end

  private
  def tweet_params
    params.require(:game_tweet).permit(:game_title_id, :tweet).merge(user_id: current_user.id)
  end

  def set_mygame
    if user_signed_in?
      @mygame = @game.find_by(user_id: current_user.id)
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @game = Game.find_by(game_title_id: params[:game_title_id])
  end
  
  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.game_title_id = params[:game_title_id]
    if @game.valid?
      @game.save
      redirect_to games_path(game_title_id: params[:game_title_id])
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def game_params
    params.require(:game).permit(:game_title_id, :player_name, :rank, :clan, :playstyle, :image).merge(user_id: current_user.id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/game_tweets/index.html.erb
<%= render "shared/header" %>
  
<div class="contents
<% case params[:game_title_id] %>
<% when nil then %>
  gameback10
<% when "1" then %>
  gameback1
<% when "2" then %>
  gameback2
<% when "3" then %>
  gameback3
<% end %>">
  <%= render "shared/left-side-bar" %>

  <div class="tweet-content">
    <%# @game_tweets.each do |tweet| %>
    <div class="content_post" >
      <div class="lower-message">
        <div class="message-content">
          おはよう
        </div>
      </div>
      <div class="user-name">
        Tom
      </div>
    </div>
    <%# end %>
    <%= form_with model: @game_tweet, url:game_tweets_path(game_title_id: params[:game_title_id]), class: "tweet-footer", local: true do |f| %>
      <div class="tweet-form">
        <%= f.text_field :tweet, class:"form-message", placeholder: "type a message" %> 
      </div>
      <%= f.submit "送信", class:"form-submit" %>
    <% end %>
  </div>

  <%= render "shared/right-side-bar" %>
</div>

app/views/games/index.html.erb
<%= render "shared/header" %>
  
<div class="contents
<% case params[:game_title_id] %>
<% when nil then %>
  gameback10
<% when "1" then %>
  gameback1
<% when "2" then %>
  gameback2
<% when "3" then %>
  gameback3
<% end %>">
  <%= render "shared/left-side-bar" %>

  <div class="main-content">
    <ul class="game-index">
      <% GameTitle.all.each do |game_title| %>
        <li class="game-content">
          <%= link_to game_tweets_path(game_title_id: game_title.id) do %>
              <%= image_tag game_title.image_path, class: 'logo-img'  %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>

  <%= render "shared/right-side-bar" %>
</div>

app/views/games/new.html.erb
<%= render "shared/header" %>
  
<div class="contents">
  <%= render "shared/left-side-bar2" %>

  <div class="main-content">
    <h2 class="items-sell-title">ゲームの情報を入力</h2>
    <%= form_with model: @game, url: games_path(game_title_id: params[:game_title_id]), local: true do |f| %>

      
      <%# 画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
          推しキャラorプレイヤー画像
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"item-image" %>
        </div>
      </div>
      <%# /画像 %>

      <%# プレイヤー情報 %>
      <div class="new-items">
        <div class="weight-bold-text">
          プレイヤー名
        </div>
        <%= f.text_field :player_name, class:"price-input", id:"item-name", placeholder:"プレイヤー名（40文字まで)", maxlength:"40" %>
        <div class="weight-bold-text">
          RANK
        </div>
        <%= f.text_field :rank, class:"price-input", id:"item-price", placeholder:"ランク入力" %>
        <div class="weight-bold-text">
          クラン名
        </div>
        <%= f.text_field :clan, class:"price-input", id:"item-price", placeholder:"クラン名入力" %>
        <div class="items-explain">
          <div class="weight-bold-text">
            プレイスタイル
          </div>
          <%= f.text_area :style, class:"items-text", id:"item-info", placeholder:"プレイスタイル" ,maxlength:"1000" %>
        </div>
        <div class="sell-btn-contents">
          <%= f.submit "登録する" ,class:"sell-btn" %>
          <%=link_to 'もどる', games_path(game_title_id: params[:game_title_id]), class:"back-btn" %>
        </div>
      </div>
      <%# /プレイヤー情報 %>
      <% end %>
  </div>

  <%= render "shared/right-side-bar" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamegroup</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <%= link_to image_tag("gamegroup.png", class:"gamegroup-icon"), "/" %>
  <div class='game-top'>
    <div class='nav'>
      <ul class='list'>
        <% if user_signed_in? %>
          <li><%= link_to current_user.name, "#", class: "user-name" %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, data:{ turbo_method: :delete }, class: "logout" %></li>
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_left-side-bar.html.erb
<div class='left-side-bar'>
  <div class='user-contents'>

    <% if user_signed_in? && params[:game_title_id] != nil %>
      <% unless @game.exists?(user_id: current_user.id) %>
        <%= link_to new_game_path(game_title_id: params[:game_title_id]), class: 'purchase-btn' do %>
        <%= image_tag 'icon_game.png' , size: '185x50' ,class: "purchase-btn-icon" %>
        <% end %>
      <% else %>
        <div class='player-date'>
          <%= image_tag @mygame.image, class: 'chara-img' %>
          <div class='player-info'>
            <h3 class='player-name'>
            プレイヤー名：
              <%= @mygame.player_name %>
            </h3>
            <div class='player-rank'>
            ランク：
              <%= @mygame.rank %>
            </div>
            <div class='player-clan'>
            クラン名：
              <%= @mygame.clan %>
            </div>
            <div class='player-style'>
            プレイスタイル：
              <%= @mygame.playstyle %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_left-side-bar2.html.erb
<div class='left-side-bar'>
  <div class='user-contents'>

    
  </div>
</div>

app/views/shared/_right-side-bar.html.erb
<div class='right-side-bar'>
  <div class='user-contents'>
  
    <div class='player-date'>
      <%# image_tag @game.image, class: 'chara-img' %>
      <%= image_tag("test1.png",class: 'chara-img')  %>
      <div class='player-info'>
        <h3 class='player-name'>
        プレイヤー名：ヴァンピィ
          <%# game.player_name %>
        </h3>
        <div class='player-rank'>
        ランク：5
          <%# game.rank %>
        </div>
        <div class='player-clan'>
        クラン名：あああ
          <%# game.clan %>
        </div>
        <div class='player-style'>
        プレイスタイル：時々
          <%# game.playstyle %>
        </div>
      </div>
    </div>
  </div>
</div>